server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: shakib19
    url: jdbc:mysql://localhost:3306/noteApp
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show:
      show-sql: true
    database: mysql